import type { Config } from "tailwindcss";

const config: Config = {
    darkMode: ["class"],
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    DEFAULT: "#2E5090",
                    50: "#EBF0F8",
                    100: "#D7E1F1",
                    200: "#AFC3E3",
                    300: "#87A5D5",
                    400: "#5F87C7",
                    500: "#2E5090",
                    600: "#254073",
                    700: "#1C3056",
                    800: "#132039",
                    900: "#0A101C",
                },
                secondary: {
                    DEFAULT: "#1F4E78",
                    50: "#E8EEF4",
                    100: "#D1DDE9",
                    200: "#A3BBD3",
                    300: "#7599BD",
                    400: "#4777A7",
                    500: "#1F4E78",
                    600: "#193E60",
                    700: "#132F48",
                    800: "#0C1F30",
                    900: "#061018",
                },
                accent: {
                    DEFAULT: "#5B9BD5",
                    50: "#EFF6FC",
                    100: "#DFEDF9",
                    200: "#BFDBF3",
                    300: "#9FC9ED",
                    400: "#7FB7E7",
                    500: "#5B9BD5",
                    600: "#497CAA",
                    700: "#375D7F",
                    800: "#253E54",
                    900: "#121F2A",
                },
                success: {
                    DEFAULT: "#28A745",
                    50: "#E9F7ED",
                    100: "#D3EFDB",
                    200: "#A7DFB7",
                    300: "#7BCF93",
                    400: "#4FBF6F",
                    500: "#28A745",
                    600: "#208637",
                    700: "#186429",
                    800: "#10431C",
                    900: "#08210E",
                },
                warning: {
                    DEFAULT: "#FFC107",
                    50: "#FFF9E5",
                    100: "#FFF3CC",
                    200: "#FFE799",
                    300: "#FFDB66",
                    400: "#FFCF33",
                    500: "#FFC107",
                    600: "#CC9A06",
                    700: "#997404",
                    800: "#664D03",
                    900: "#332701",
                },
                danger: {
                    DEFAULT: "#DC3545",
                    50: "#FBEBED",
                    100: "#F7D7DB",
                    200: "#EFAFB7",
                    300: "#E78793",
                    400: "#DF5F6F",
                    500: "#DC3545",
                    600: "#B02A37",
                    700: "#842029",
                    800: "#58151C",
                    900: "#2C0B0E",
                },
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                chart: {
                    "1": "hsl(var(--chart-1))",
                    "2": "hsl(var(--chart-2))",
                    "3": "hsl(var(--chart-3))",
                    "4": "hsl(var(--chart-4))",
                    "5": "hsl(var(--chart-5))",
                },
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            fontFamily: {
                sans: ["Inter", "system-ui", "sans-serif"],
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};

export default config;
