import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { SmartKitStats } from './types';

export const CoverPageService = {
  /**
   * Generates a single-page PDFDocument containing the Cover Page.
   */
  async generateCoverPage(
    schemeName: string,
    applicantName: string,
    stats: SmartKitStats,
    documentCount: number
  ): Promise<PDFDocument> {
    const pdfDoc = await PDFDocument.create();
    
    // Create A4 page (portrait: 595.28 x 841.89)
    const page = pdfDoc.addPage([595.28, 841.89]);
    
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
    
    const pageW = page.getWidth();
    const pageH = page.getHeight();
    
    // Draw Header
    const titleText = 'Smart Document Kit';
    const titleWidth = fontBold.widthOfTextAtSize(titleText, 28);
    page.drawText(titleText, {
      x: (pageW - titleWidth) / 2,
      y: pageH - 120,
      size: 28,
      font: fontBold,
      color: rgb(0.2, 0.2, 0.4),
    });
    
    // Draw Scheme Name
    const schemeWidth = fontBold.widthOfTextAtSize(schemeName, 20);
    page.drawText(schemeName, {
      x: (pageW - schemeWidth) / 2,
      y: pageH - 160,
      size: 20,
      font: fontBold,
      color: rgb(0.1, 0.1, 0.8),
    });
    
    // Draw Details
    const startY = pageH - 240;
    const lineSpacing = 30;
    
    const details = [
      { label: 'Applicant Name:', value: applicantName },
      { label: 'Generation Date:', value: new Date().toLocaleDateString() },
      { label: 'Total Documents:', value: documentCount.toString() },
      { label: 'Readiness Score:', value: `${stats.readiness}%` },
      { label: 'Validated:', value: `${stats.validated} / ${stats.required}` }
    ];
    
    details.forEach((detail, idx) => {
      const y = startY - (idx * lineSpacing);
      page.drawText(detail.label, {
        x: 100,
        y,
        size: 14,
        font: fontBold,
        color: rgb(0.3, 0.3, 0.3)
      });
      
      page.drawText(detail.value, {
        x: 260,
        y,
        size: 14,
        font: fontRegular,
        color: rgb(0, 0, 0)
      });
    });
    
    // Footer
    const footerText = 'Generated by Saral Sahayta Document Engine';
    const footerWidth = fontRegular.widthOfTextAtSize(footerText, 10);
    page.drawText(footerText, {
      x: (pageW - footerWidth) / 2,
      y: 50,
      size: 10,
      font: fontRegular,
      color: rgb(0.5, 0.5, 0.5)
    });
    
    return pdfDoc;
  }
};
